### ISSUE TITLE
"Cannot assign to theme in self" error

### ISSUE THREAD

**Issue by code-K** [mysterioustrousers/MYSForms#10]
Hi there,

since i updated with your last changes to the theming i now get an error when instantiate a theme:

```swift
// set a form-wide theme
self.theme = MYSFormTheme()
```

This drops me an error of: "Cannot assign to theme in self"

Does it mean i should not do this anymore and instead directly assign values to self.theme?

Also now if i leave it out and only directly changing the values from self.theme they seem to be not covered completely? For example i set background color to white but the whole background is now light gray or so.? Or did you change the backgroundColor now?

I need it to be complete white.

I've also attached your example. There's also not the white background anymore...
![bildschirmfoto 2015-03-15 um 10 52 26](https://cloud.githubusercontent.com/assets/1224750/6655424/b412fbe4-cb01-11e4-97fe-13e17c0d3e7e.png)

Thanks much for help and best regards,
Chris

**Comment by code-K** [comment]
Please ignore.. i found a mistake on my end...

**Comment by atomkirk** [comment]
Right. Default themes are already present in read only theme properties. You can modify their values or merge themes onto them.
