### ISSUE TITLE
receive Notifications on Form updates?

### ISSUE THREAD

**Issue by code-K** [mysterioustrousers/MYSForms#6]
Hi there, i really like your MYSForms and i started using it in a project but now i have a question. :)
Is there any possibility to easily receive notifications when any form values changed? 
So like that the form always gets submitted automatically with any value changes?

Thanks much for feedback and best regards,
Christian

**Comment by atomkirk** [comment]
You can be a delegate for the form and there is a method to be notified. 

If you dont want your application model to be bound to the form you can supply a mutable dictionary as the form model and extract the values when youre ready. 

You can also use validations to make sure values are valid. 

Lastly, i like the idea of a revert method that sets all a models values back to their original values…

**Comment by code-K** [comment]
Perfect, thanks much! I've totally overseen it! ^^

Just implemented the delegate and set it to self and it works fine...

```swift
class ErstattungsCheckCollectionViewController: MYSFormViewController, **MYSFormViewControllerDelegate** { 
```

```swift
override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        if self.model == nil {
            self.model = AppDelegate().dataModel
            myData = self.model as! DataModel
        }
        
        **self.formDelegate = self**
        
        //println(self.vc)
        self.collectionView?.contentInset = UIEdgeInsetsMake(20, 0, 20, 0)
    }
```

```swift
override func formViewController(controller: MYSFormViewController!, didUpdateModelWithValue value: AnyObject!, element: MYSFormElement!) {
        //
        println("formViewController didUpdateModelWithValue")
    }
```
