### ISSUE TITLE
Having normal pickerelement at the bottom (actionsheet) instead inline ?

### ISSUE THREAD

**Issue by code-K** [mysterioustrousers/MYSForms#7]
Hi there again, i've one more question, is it possible to have the pickerelement displayed normally at the bottom instead of inline?

also when assigning the PresenceValidation to a pickerelement, it's not validating when selected ?

```swift
pickerField.addFormValidation(MYSFormPresenceValidation())
```
it's then always not valid even when selected a value from the picker.?

Thanks much for feedback and best regards,
Chris

**Comment by atomkirk** [comment]
you're first question: no not really. the human interface guidelines for ios 7+ say it should be displayed in-line.

and I will look into the second, i think that could be a bug

**Comment by code-K** [comment]
Thanks much for looking into it! Then i'll stick to the inline version. :)

Let me know if you find anything out about the validation problem.

Thanks much and best regards,
C

**Comment by code-K** [comment]
Is there a possibility to easily "close/collapse" an picker element when selecting another picker element or even click anywhere else in the view?

i tested with, but didn't work.
```swift
pickerField.datePicker.endEditing(true)
```

**Comment by atomkirk** [comment]
No but thats a good idea. Make a new issue for that feature r



- Adam Kirk
